<?php 
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_5563627e01706',
	'title' => 'Custom Page Layout',
	'fields' => array (
		array (
			'key' => 'field_556392aa43b9d',
			'label' => 'Content Sections',
			'name' => 'content_sections',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Add Section',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '556392cc5033d',
					'name' => 'content_section',
					'label' => 'Content Section',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_55bfd8b13bf48',
							'label' => 'Section Heading',
							'name' => 'section_heading',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_55bfd8db3bf49',
							'label' => 'Section Subheading',
							'name' => 'section_subheading',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => 3,
							'new_lines' => 'br',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_55639d3d2737e',
							'label' => 'Layout Row',
							'name' => 'layout_row',
							'type' => 'flexible_content',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'button_label' => 'Add New Row',
							'min' => '',
							'max' => '',
							'layouts' => array (
								array (
									'key' => '55639d9a3c1b6',
									'name' => 'one_column_row',
									'label' => 'One Column Row',
									'display' => 'block',
									'sub_fields' => array (
										array (
											'key' => 'field_55639e7753b0f',
											'label' => 'Column',
											'name' => 'column_1',
											'type' => 'wysiwyg',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'tabs' => 'all',
											'toolbar' => 'full',
											'media_upload' => 1,
										),
										array (
											'key' => 'field_55ae9af71bb26',
											'label' => 'Column Layout (desktop)',
											'name' => 'md_column_layout',
											'type' => 'select',
											'instructions' => '',
											'required' => 1,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => 25,
												'class' => '',
												'id' => '',
											),
											'choices' => array (
												'0-12-0' => 'Full Width',
												'2-8-2' => '- ⅔ -',
												'3-6-3' => '- ½ -',
											),
											'default_value' => array (
												'0-12-0' => '0-12-0',
											),
											'allow_null' => 0,
											'multiple' => 0,
											'ui' => 0,
											'ajax' => 0,
											'placeholder' => '',
											'disabled' => 0,
											'readonly' => 0,
										),
										array (
											'key' => 'field_55ae9b0c1bb27',
											'label' => 'Column Layout (tablet)',
											'name' => 'sm_column_layout',
											'type' => 'select',
											'instructions' => '',
											'required' => 1,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => 25,
												'class' => '',
												'id' => '',
											),
											'choices' => array (
												'0-12-0' => 'Full Width',
												'2-8-2' => '- ⅔ -',
												'3-6-3' => '- ½ -',
											),
											'default_value' => array (
												'0-12-0' => '0-12-0',
											),
											'allow_null' => 0,
											'multiple' => 0,
											'ui' => 0,
											'ajax' => 0,
											'placeholder' => '',
											'disabled' => 0,
											'readonly' => 0,
										),
									),
									'min' => '',
									'max' => '',
								),
								array (
									'key' => '55639eb453b10',
									'name' => 'two_column_row',
									'label' => 'Two Column Row',
									'display' => 'block',
									'sub_fields' => array (
										array (
											'key' => 'field_55639eec53b11',
											'label' => 'Column 1',
											'name' => 'column_1',
											'type' => 'wysiwyg',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => 50,
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'tabs' => 'all',
											'toolbar' => 'full',
											'media_upload' => 1,
										),
										array (
											'key' => 'field_55639f1f53b12',
											'label' => 'Column 2',
											'name' => 'column_2',
											'type' => 'wysiwyg',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => 50,
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'tabs' => 'all',
											'toolbar' => 'full',
											'media_upload' => 1,
										),
										array (
											'key' => 'field_55639f9f53b17',
											'label' => 'Column Layout (desktop)',
											'name' => 'md_column_layout',
											'type' => 'select',
											'instructions' => '',
											'required' => 1,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => 25,
												'class' => '',
												'id' => '',
											),
											'choices' => array (
												'3-9' => '¼ - ¾',
												'4-8' => '⅓ - ⅔',
												'6-6' => '½ - ½',
												'8-4' => '⅔ - ⅓',
												'9-3' => '¾ - ¼',
											),
											'default_value' => array (
												'6-6' => '6-6',
											),
											'allow_null' => 0,
											'multiple' => 0,
											'ui' => 0,
											'ajax' => 0,
											'placeholder' => '',
											'disabled' => 0,
											'readonly' => 0,
										),
										array (
											'key' => 'field_55ae6604560e0',
											'label' => 'Column Layout (tablet)',
											'name' => 'sm_column_layout',
											'type' => 'select',
											'instructions' => '',
											'required' => 1,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => 25,
												'class' => '',
												'id' => '',
											),
											'choices' => array (
												'12-12' => 'Full Width',
												'3-9' => '¼ - ¾',
												'4-8' => '⅓ - ⅔',
												'6-6' => '½ - ½',
												'8-4' => '⅔ - ⅓',
												'9-3' => '¾ - ¼',
											),
											'default_value' => array (
												'12-12' => '12-12',
											),
											'allow_null' => 0,
											'multiple' => 0,
											'ui' => 0,
											'ajax' => 0,
											'placeholder' => '',
											'disabled' => 0,
											'readonly' => 0,
										),
										array (
											'key' => 'field_55ae69378538a',
											'label' => 'Column Layout (mobile)',
											'name' => 'xs_column_layout',
											'type' => 'select',
											'instructions' => '',
											'required' => 1,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => 25,
												'class' => '',
												'id' => '',
											),
											'choices' => array (
												'12-12' => 'Full Width',
												'4-8' => '⅓ - ⅔',
												'6-6' => '½ - ½',
												'8-4' => '⅔ - ⅓',
											),
											'default_value' => array (
												'12-12' => '12-12',
											),
											'allow_null' => 0,
											'multiple' => 0,
											'ui' => 0,
											'ajax' => 0,
											'placeholder' => '',
											'disabled' => 0,
											'readonly' => 0,
										),
										array (
											'key' => 'field_55ae6b598538f',
											'label' => 'Swap Columns',
											'name' => 'swap_columns',
											'type' => 'true_false',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => 25,
												'class' => '',
												'id' => '',
											),
											'message' => '',
											'default_value' => 0,
										),
									),
									'min' => '',
									'max' => '',
								),
								array (
									'key' => '55639f3153b13',
									'name' => 'three_column_row',
									'label' => 'Three Column Row',
									'display' => 'block',
									'sub_fields' => array (
										array (
											'key' => 'field_55639f4f53b14',
											'label' => 'Column 1',
											'name' => 'column_1',
											'type' => 'wysiwyg',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => 33,
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'tabs' => 'all',
											'toolbar' => 'full',
											'media_upload' => 1,
										),
										array (
											'key' => 'field_55639f8553b15',
											'label' => 'Column 2',
											'name' => 'column_2',
											'type' => 'wysiwyg',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => 33,
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'tabs' => 'all',
											'toolbar' => 'full',
											'media_upload' => 1,
										),
										array (
											'key' => 'field_55639f8e53b16',
											'label' => 'Column 3',
											'name' => 'column_3',
											'type' => 'wysiwyg',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => 33,
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'tabs' => 'all',
											'toolbar' => 'full',
											'media_upload' => 1,
										),
										array (
											'key' => 'field_55aaae2ad22b2',
											'label' => 'Column Layout (desktop)',
											'name' => 'md_column_layout',
											'type' => 'select',
											'instructions' => '',
											'required' => 1,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => 25,
												'class' => '',
												'id' => '',
											),
											'choices' => array (
												'4-4-4' => '⅓ - ⅓ - ⅓',
												'3-3-6' => '¼ - ¼ - ½',
												'3-6-3' => '¼ - ½ - ¼',
												'6-3-3' => '½ - ¼ - ¼',
											),
											'default_value' => array (
												'4-4-4' => '4-4-4',
											),
											'allow_null' => 0,
											'multiple' => 0,
											'ui' => 0,
											'ajax' => 0,
											'placeholder' => '',
											'disabled' => 0,
											'readonly' => 0,
										),
										array (
											'key' => 'field_55ae67de560e1',
											'label' => 'Column Layout (tablet)',
											'name' => 'sm_column_layout',
											'type' => 'select',
											'instructions' => '',
											'required' => 1,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => 25,
												'class' => '',
												'id' => '',
											),
											'choices' => array (
												'12-12-12' => 'Full Width',
												'4-4-4' => '⅓ - ⅓ - ⅓',
												'3-3-6' => '¼ - ¼ - ½',
												'3-6-3' => '¼ - ½ - ¼',
												'6-3-3' => '½ - ¼ - ¼',
												'6-6-12' => '½ - ½ - Full',
												'12-6-6' => 'Full - ½ - ½',
											),
											'default_value' => array (
												'4-4-4' => '4-4-4',
											),
											'allow_null' => 0,
											'multiple' => 0,
											'ui' => 0,
											'ajax' => 0,
											'placeholder' => '',
											'disabled' => 0,
											'readonly' => 0,
										),
										array (
											'key' => 'field_55ae699e8538b',
											'label' => 'Column Layout (mobile)',
											'name' => 'xs_column_layout',
											'type' => 'select',
											'instructions' => '',
											'required' => 1,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => 25,
												'class' => '',
												'id' => '',
											),
											'choices' => array (
												'12-12-12' => 'Full Width',
												'4-4-4' => '⅓ - ⅓ - ⅓',
												'6-6-12' => '½ - ½ - Full',
												'12-6-6' => 'Full - ½ - ½',
											),
											'default_value' => array (
												'12-12-12' => '12-12-12',
											),
											'allow_null' => 0,
											'multiple' => 0,
											'ui' => 0,
											'ajax' => 0,
											'placeholder' => '',
											'disabled' => 0,
											'readonly' => 0,
										),
									),
									'min' => '',
									'max' => '',
								),
								array (
									'key' => '5563a0cf53b19',
									'name' => 'four_column_row',
									'label' => 'Four Column Row',
									'display' => 'block',
									'sub_fields' => array (
										array (
											'key' => 'field_5563a0cf53b1a',
											'label' => 'Column 1',
											'name' => 'column_1',
											'type' => 'wysiwyg',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => 25,
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'tabs' => 'all',
											'toolbar' => 'full',
											'media_upload' => 1,
										),
										array (
											'key' => 'field_5563a0cf53b1b',
											'label' => 'Column 2',
											'name' => 'column_2',
											'type' => 'wysiwyg',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => 25,
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'tabs' => 'all',
											'toolbar' => 'full',
											'media_upload' => 1,
										),
										array (
											'key' => 'field_5563a0cf53b1c',
											'label' => 'Column 3',
											'name' => 'column_3',
											'type' => 'wysiwyg',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => 25,
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'tabs' => 'all',
											'toolbar' => 'full',
											'media_upload' => 1,
										),
										array (
											'key' => 'field_5563a0e153b1d',
											'label' => 'Column 4',
											'name' => 'column_4',
											'type' => 'wysiwyg',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => 25,
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'tabs' => 'all',
											'toolbar' => 'full',
											'media_upload' => 1,
										),
										array (
											'key' => 'field_55ae6a038538c',
											'label' => 'Column Layout (desktop)',
											'name' => 'md_column_layout_copy',
											'type' => 'select',
											'instructions' => '',
											'required' => 1,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => 25,
												'class' => '',
												'id' => '',
											),
											'choices' => array (
												'3-3-3-3' => '¼ - ¼ - ¼ - ¼',
											),
											'default_value' => array (
												'3-3-3-3' => '3-3-3-3',
											),
											'allow_null' => 0,
											'multiple' => 0,
											'ui' => 0,
											'ajax' => 0,
											'placeholder' => '',
											'disabled' => 0,
											'readonly' => 0,
										),
										array (
											'key' => 'field_55ae6aa18538e',
											'label' => 'Column Layout (tablet)',
											'name' => 'sm_column_layout',
											'type' => 'select',
											'instructions' => '',
											'required' => 1,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => 25,
												'class' => '',
												'id' => '',
											),
											'choices' => array (
												'12-12-12-12' => 'Full Width',
												'3-3-3-3' => '¼ - ¼ - ¼ - ¼',
												'6-6-6-6' => '½ - ½ - ½ - ½',
											),
											'default_value' => array (
												'6-6-6-6' => '6-6-6-6',
											),
											'allow_null' => 0,
											'multiple' => 0,
											'ui' => 0,
											'ajax' => 0,
											'placeholder' => '',
											'disabled' => 0,
											'readonly' => 0,
										),
										array (
											'key' => 'field_55ae6a9b8538d',
											'label' => 'Column Layout (mobile)',
											'name' => 'xs_column_layout',
											'type' => 'select',
											'instructions' => '',
											'required' => 1,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => 25,
												'class' => '',
												'id' => '',
											),
											'choices' => array (
												'12-12-12-12' => 'Full Width',
												'6-6-6-6' => '½ - ½ - ½ - ½',
											),
											'default_value' => array (
												'12-12-12-12' => '12-12-12-12',
											),
											'allow_null' => 0,
											'multiple' => 0,
											'ui' => 0,
											'ajax' => 0,
											'placeholder' => '',
											'disabled' => 0,
											'readonly' => 0,
										),
									),
									'min' => '',
									'max' => '',
								),
								array (
									'key' => '55ae590272c5e',
									'name' => 'row_separator',
									'label' => 'Row Separator',
									'display' => 'row',
									'sub_fields' => array (
										array (
											'key' => 'field_55ae593772c5f',
											'label' => 'Clear Screen Size',
											'name' => 'clear_screen_size',
											'type' => 'select',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'choices' => array (
												'visible-xs-block' => 'Only On Mobile',
												'visible-sm-block' => 'Only On Tablet',
												'visible-md-block' => 'Only On Desktop',
											),
											'default_value' => array (
												'visible-xs-block' => 'visible-xs-block',
											),
											'allow_null' => 0,
											'multiple' => 0,
											'ui' => 0,
											'ajax' => 0,
											'placeholder' => '',
											'disabled' => 0,
											'readonly' => 0,
										),
									),
									'min' => '',
									'max' => '',
								),
								array (
									'key' => '55afb24793789',
									'name' => 'section_break',
									'label' => 'Section Break',
									'display' => 'row',
									'sub_fields' => array (
										array (
											'key' => 'field_55afb6199378a',
											'label' => 'Use Icon',
											'name' => 'use_section_icon',
											'type' => 'true_false',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array (
												'width' => 40,
												'class' => '',
												'id' => '',
											),
											'message' => '<a href="http://fortawesome.github.io/Font-Awesome/icons/" target="_blank">Browse FontAwesome Icons</a>',
											'default_value' => 1,
										),
										array (
											'key' => 'field_55afbc319378b',
											'label' => 'Section Break Icon',
											'name' => 'section_break_icon',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => array (
												array (
													array (
														'field' => 'field_55afb6199378a',
														'operator' => '==',
														'value' => '1',
													),
												),
											),
											'wrapper' => array (
												'width' => 60,
												'class' => '',
												'id' => '',
											),
											'default_value' => '<i class="fa fa-arrow-circle-down"></i>',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
											'readonly' => 0,
											'disabled' => 0,
										),
									),
									'min' => '',
									'max' => '',
								),
							),
						),
						array (
							'key' => 'field_556367f16e26e',
							'label' => 'Section ID',
							'name' => 'section_id',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 25,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'e.g. how-it-works',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_556369a56e26f',
							'label' => 'Section Class',
							'name' => 'section_class',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 25,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'e.g. callout',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_556399df2737d',
							'label' => 'Content Class',
							'name' => 'content_class',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 25,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'e.g. alert alert-info',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5563951a43ba1',
							'label' => 'Inline Content Styles',
							'name' => 'content_inline_styles',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 25,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'e.g. color: #333; border: 1px solid #ccc;',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_556365a8f2f2e',
							'label' => 'Section Width',
							'name' => 'section_width',
							'type' => 'select',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 30,
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'container' => 'Normal',
								'container-fluid' => 'Full Width',
							),
							'default_value' => array (
								'container' => 'container',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'disabled' => 0,
							'readonly' => 0,
						),
						array (
							'key' => 'field_556366ecf2f2f',
							'label' => 'Section Background',
							'name' => 'section_background',
							'type' => 'select',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 30,
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'transparent' => 'Transparent',
								'color' => 'Solid Color',
							),
							'default_value' => array (
								'transparent' => 'transparent',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'disabled' => 0,
							'readonly' => 0,
						),
						array (
							'key' => 'field_556371a4500be',
							'label' => 'Background Color',
							'name' => 'background_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_556366ecf2f2f',
										'operator' => '==',
										'value' => 'color',
									),
								),
							),
							'wrapper' => array (
								'width' => 40,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/custom-page-layout.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'custom_fields',
		2 => 'discussion',
		3 => 'comments',
		4 => 'slug',
		5 => 'author',
		6 => 'format',
		7 => 'featured_image',
		8 => 'categories',
		9 => 'tags',
		10 => 'send-trackbacks',
	),
));

acf_add_local_field_group(array (
	'key' => 'group_55bc176f9f94b',
	'title' => 'Page Headline',
	'fields' => array (
		array (
			'key' => 'field_55bc177fa07da',
			'label' => 'Headline Display',
			'name' => 'headline_display',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'default' => 'Page Title (default)',
				'alternate' => 'Alternate Headline',
				'none' => 'Do not display a title',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'default',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_55bc1970a07db',
			'label' => 'Alternate Headline',
			'name' => 'alternate_headline',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55bc177fa07da',
						'operator' => '==',
						'value' => 'alternate',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 20,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

endif;


// Options Pages
if( function_exists('acf_add_options_page') ) {
	
	acf_add_options_page(array(
		'page_title' 	=> 'General Theme Settings',
		'menu_title'	=> 'Theme Settings',
		'menu_slug' 	=> 'general-theme-settings',
		'capability'	=> 'edit_posts',
		'redirect'		=> false
	));
	
	acf_add_options_sub_page(array(
		'page_title' 	=> 'Socicons',
		'menu_title'	=> 'Socicons',
		'parent_slug'	=> 'general-theme-settings',
	));
	
	acf_add_options_sub_page(array(
		'page_title' 	=> 'Header & Footer Settings',
		'menu_title'	=> 'Header & Footer',
		'parent_slug'	=> 'general-theme-settings',
	));
	
}

// Socicons Options
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_55c120a09df53',
	'title' => 'Social Media Icons',
	'fields' => array (
		array (
			'key' => 'field_55f6054e0dbc5',
			'label' => 'Socicon Placement',
			'name' => 'socicon_placement',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'header' => 'Header',
				'sidebar' => 'Sidebar',
				'footer' => 'Footer',
			),
			'default_value' => array (
			),
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_55f616b2544c5',
			'label' => 'Socicon Size',
			'name' => 'socicon_size',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'size-24' => 'Small (24px)',
				'size-36' => 'Medium (36px)',
				'size-48' => 'Large (48px)',
				'size-64' => 'Extra Large (64px)',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_55f605b50dbc6',
			'label' => 'Socicon Style',
			'name' => 'socicon_style',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'circles' => 'Circles',
				'soft-corners' => 'Soft Round Corners',
				'hard-corners' => 'Hard Round Corners',
				'squares' => 'Squares',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'Circles',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_55f606e3ec579',
			'label' => 'Socicon Color',
			'name' => 'socicon_color',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'normal-bg' => 'Normal',
				'inverse-bg' => 'Inverse',
				'custom-bg' => 'Custom Background',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'Normal',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_55f6067f0dbc7',
			'label' => 'Socicon Shadow',
			'name' => 'socicon_shadow',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'no-shadow' => 'None',
				'drop-shadow' => 'Drop Shadow',
				'inset-shadow' => 'Inset Shadow',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'None',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_55c121672bac1',
			'label' => 'Socicons',
			'name' => 'socicon',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Socicon',
			'sub_fields' => array (
				array (
					'key' => 'field_55c121ee2bac2',
					'label' => 'Socicon Type',
					'name' => 'socicon_type',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 30,
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'facebook' => 'Facebook',
						'twitter' => 'Twitter',
						'linkedin' => 'LinkedIn',
						'google-plus' => 'Google+',
						'youtube' => 'YouTube',
						'vimeo' => 'Vimeo',
						'instagram' => 'Instagram',
						'pinterest' => 'Pinterest',
						'tumblr' => 'Tumblr',
						'xing' => 'Xing',
						'stumbleupon' => 'StumbleUpon',
						'slack' => 'Slack',
						'yelp' => 'Yelp',
						'foursquare' => 'Foursquare',
						'skype' => 'Skype',
						'share-alt' => 'Share',
						'rss' => 'RSS',
						'car' => 'Directions (car)',
						'map-o' => 'Directions (map)',
						'phone' => 'Phone',
						'inbox' => 'Email',
					),
					'default_value' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_55c125822bac3',
					'label' => 'Socicon Link',
					'name' => 'socicon_link',
					'type' => 'text',
					'instructions' => 'Enter the full link to your profile. For phone numbers: "tel:2039990000"',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 40,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'http://linkto.com/yourprofile',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-socicons',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;

 ?>